services:
  whatsapp_go:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    container_name: whatsapp
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - whatsapp:/app/storages
    env_file:
        - ./.env

  whatsapp_python:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - "5555:5000"
    env_file:
      - ./.env
    networks:
      - hxnid-network
    depends_on:
      - whatsapp_go

networks:
  hxnid-network:
    driver: bridge

volumes:
  whatsapp:
