services:
  whatsapp_go:
    build:
      context: .
      dockerfile: go-multidevice.Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - hxnid-network

  whatsapp_python:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./python-wa-bot
      dockerfile: ./docker/python.Dockerfile
    restart: "on-failure"
    ports:
      - "5555:5000"
    env_file:
      - ./.env
    networks:
      - hxnid-network
    depends_on:
      - whatsapp_go

networks:
  hxnid-network:
    driver: bridge
