services:
  whatsapp_go:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    container_name: whatsapp
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=true
      - --os=Chrome
      - --account-validation=false
      - --webhook=http://whatsapp_python:5050/webhook

  whatsapp_python:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
    restart: "on-failure"
    ports:
      - "5555:5000"
    env_file:
      - ./.env
    networks:
      - hxnid-network
    depends_on:
      - whatsapp_go

networks:
  hxnid-network:
    driver: bridge

volumes:
  whatsapp:
